on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "this is first step"
      - name: second step
        run: mkdir sam && cd sam && pwd

        
